<a href="https://colab.research.google.com/github/vatsaljoshi/demo-repo/blob/main/K_N_N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#zoo database from below link
#url="https://archive.ics.uci.edu/ml/machine-learning-databases/tic-tac-toe/tic-tac-toe.data"
url="https://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data"
#assigning column names to dataset
names=['Column A','Column B','Column C','Column D','class']
#read dataset to dataframe
dataset=pd.read_csv(url,names=names)

In [ ]:
dataset.head()

Column A  Column B  Column C  Column D  class
aardvark 1 0 0 1 0 0 1 1 1 1 0 0         4         0         0         1      1
antelope 1 0 0 1 0 0 0 1 1 1 0 0         4         1         0         1      1
bass     0 0 1 0 0 1 1 1 1 0 0 1         0         1         0         0      4
bear     1 0 0 1 0 0 1 1 1 1 0 0         4         0         0         1      1
boar     1 0 0 1 0 0 1 1 1 1 0 0         4         1         0         1      1

In [ ]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, 4].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      0.78      0.88         9
           2       0.71      1.00      0.83         5
           4       1.00      1.00      1.00         1
           5       0.00      0.00      0.00         0
           6       0.75      1.00      0.86         3
           7       1.00      0.33      0.50         3

    accuracy                           0.81        21
   macro avg       0.74      0.69      0.68        21
weighted avg       0.90      0.81      0.81        21

[[7 2 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 3 0]
 [0 0 0 1 1 1]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
